server:
  contextPath: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  jmx:
    enabled: true

jmx:
  rmi:
    port: 9001
    host: localhost

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
