server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
spring:
  jmx:
    enabled: true
  resources:
    cache: 
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  version: '@springdoc.version@'

jmx:
  rmi:
    port: 9001
    host: localhost

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
